### ISSUE TITLE
中文文件名文件上传bug

### ISSUE THREAD

**Issue by Lamb-Yang** [scue/qcloud-cos-mweb#1]
你好，最近刚好要把图床搬到腾讯COS上，也和你一样在用mweb写东西，试用了一下这个工具发现在把mweb本地添加的中文名图片通过工具上传到COS后返回的链接地址转换有误。
比如，本地的图片文件在mweb里显示是`~/%E5%9F%83%E5%BE%AEP1-001.jpg`，上传之后返回的却是`~/blog/%25E5%259F%2583%25E5%25BE%25AEP1-001.jpg`。

**Comment by scue** [comment]
这个不是问题呀，默认上传的是/blog目录的。
