### ISSUE TITLE
亲测用不了，这个错怎么找？

### ISSUE THREAD

**Issue by nlpjoe** [scue/qcloud-cos-mweb#2]
![image](https://user-images.githubusercontent.com/9483969/49916762-57d80a00-fed7-11e8-864f-6e66b139a3c4.png)

**Comment by nlpjoe** [comment]
我检查了我的cos配置文件没问题，我用的coscmd 1.8.5.21，你用的是什么版本的？

**Comment by nlpjoe** [comment]
数据能传上去，但是返回不来，那块有bug。先用着cosbrowser了

**Comment by scue** [comment]
我的配置文件：

![image](https://user-images.githubusercontent.com/2650439/49980203-74367e00-ff8d-11e8-8457-c6b946d7acae.png)

我的 coscmd 版本：
```sh
╰─$ pip list | grep coscmd
coscmd                             1.8.5.5
```

**Comment by nlpjoe** [comment]
谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。

**Comment by RubiTree** [comment]
> 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。

求问怎么可以的啊，我的还是不行，匿名改成True了，也是一样，能上传成功，但处理返回结果的时候报错

**Comment by RubiTree** [comment]
> 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。

而且是一模一样的报错...

**Comment by RubiTree** [comment]
> 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。

感觉可能是MWeb的问题，你是升级了MWeb吗？

**Comment by RubiTree** [comment]
> 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。

升级了Mweb到2.3还是一样报错。。。

**Comment by scue** [comment]
> > 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。
> 
> 感觉可能是MWeb的问题，你是升级了MWeb吗？

MWeb是最新的，应该和coscmd版本有关系。

**Comment by RubiTree** [comment]
> > > 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。
> > 
> > 
> > 感觉可能是MWeb的问题，你是升级了MWeb吗？
> 
> MWeb是最新的，应该和coscmd版本有关系。

我的 coscmd 版本是 1.8.5.23，也是最新的，还是用不了 T T
我现在只能手动一遍正则替换把图片地址给换了，因为实际上还是上传成功了的，就是没法处理返回的结果

**Comment by RubiTree** [comment]
> > > 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。
> > 
> > 
> > 感觉可能是MWeb的问题，你是升级了MWeb吗？
> 
> MWeb是最新的，应该和coscmd版本有关系。

这是我的报错信息：
![image](https://user-images.githubusercontent.com/13551681/50278284-9ba3b400-0481-11e9-8729-9fda82a1567a.png)

**Comment by scue** [comment]
> > > > 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。
> > > 
> > > 
> > > 感觉可能是MWeb的问题，你是升级了MWeb吗？
> > 
> > 
> > MWeb是最新的，应该和coscmd版本有关系。
> 
> 我的 coscmd 版本是 1.8.5.23，也是最新的，还是用不了 T T
> 我现在只能手动一遍正则替换把图片地址给换了，因为实际上还是上传成功了的，就是没法处理返回的结果

你回退到 `coscmd 1.8.5.5`

**Comment by RubiTree** [comment]
> > > > > 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。
> > > > 
> > > > 
> > > > 感觉可能是MWeb的问题，你是升级了MWeb吗？
> > > 
> > > 
> > > MWeb是最新的，应该和coscmd版本有关系。
> > 
> > 
> > 我的 coscmd 版本是 1.8.5.23，也是最新的，还是用不了 T T
> > 我现在只能手动一遍正则替换把图片地址给换了，因为实际上还是上传成功了的，就是没法处理返回的结果
> 
> 你回退到 `coscmd 1.8.5.5`

怎么回退呀，看了下cosmd的release里没有1.8.5.5的版本，最新的是v1.8.4.17，可能会太早了一点

**Comment by RubiTree** [comment]
> > > > > 谢谢了，可能是版本问题，也可能是我设置了匿名为False，现在可以了。
> > > > 
> > > > 
> > > > 感觉可能是MWeb的问题，你是升级了MWeb吗？
> > > 
> > > 
> > > MWeb是最新的，应该和coscmd版本有关系。
> > 
> > 
> > 我的 coscmd 版本是 1.8.5.23，也是最新的，还是用不了 T T
> > 我现在只能手动一遍正则替换把图片地址给换了，因为实际上还是上传成功了的，就是没法处理返回的结果
> 
> 你回退到 `coscmd 1.8.5.5`

感谢感谢！直接down下了项目，按照commit记录回退到1.8.5.7（1.8.5.6和1.8.5.7好像是解决了两个bug），解决了问题，能成功上传了！非常感谢
